spring.application.name=Reto4
spring.mongodb.uri=mongodb+srv://danielmorenoolea_db_user:konodioda12@cluster0.vuorc8l.mongodb.net/Reto4?retryWrites=true&w=majority&authSource=admin
spring.mongodb.database=Reto4
server.port=8080




